services:
  mongodb:
    image: mongodb
    container_name: mongodb
    ports: 
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

    mongo_express:
      image: mongo-express
      container_name: mongo_express
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_SERVER: mongodb
      volumes:
       mongo_data: